spring.main.sources: com.test.lab04.camel.routes.Routes

management.shell.auth.simple.user.name: user
management.shell.auth.simple.user.password: password

camel:
  springboot:
    allow-use-original-message: false
    shutdown-timeout: 15
